name: 'Update Version'

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+-?**' ]
  workflow_dispatch:

defaults:
  run:
    shell:  |
            pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"

jobs:
  # This job is required because C# is assholes and dotnet publish refuses to use the version number set by the SetVersion.ps1 script.
  update-version-number:
    runs-on:  windows-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref:          'main'
          fetch-depth:  0

      - name:   Update .csproj Version
        run:    .\SetVersion.ps1 -Path radj307.ObservableImmutableList/radj307.ObservableImmutableList.csproj Version=$(git describe --tags --abbrev=0)

      - name:   Push Changes
        run:    |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add -A
                git commit -m "Update .csproj Version Numbers"
                git push origin

      - name:   Move Tag to new Commit
        run:    |
                git push origin :refs/tags/${{ github.ref_name }}
                git tag -fa ${{ github.ref_name }}
                git push -f --tags
        
# HEAD:github-actions
